version: "3.5"

volumes:
        wordpress_volume:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/user42/Inception/data/wordpress 
                        o: bind
                        type: none
        mariadb_volume:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/user42/Inception/data/mariadb
                        o: bind
                        type: none

networks:
  inception:
    name: inception

services:
############################### MARIADB ##########################################
  mariadb:
    container_name: mariadb
    image: mariadb:42
    volumes:
      - mariadb_volume:/var/lib/mysql
    build:
      context: requirements/mariadb
      args:
        - WP_ADMIN_USR=${WP_ADMIN_USR}
        - WP_ADMIN_PWD=${WP_ADMIN_PWD}
        - DB_NAME=${DB_NAME}
    environment:
      - DB_NAME
      - WP_ADMIN_USR
      - WP_ADMIN_PWD
    networks:
      - inception
    expose:
      - 3306
    restart: on-failure
############################### WORDPRESS ##########################################
  wordpress:
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/wordpress
    build:
      context: requirements/wordpress
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - DB_NAME=${DB_NAME}
        - WP_ADMIN_USR=${WP_ADMIN_USR}
        - WP_ADMIN_PWD=${WP_ADMIN_PWD}
        - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
        - WP_TITLE=${WP_TITLE}
        - WP_USR=${WP_USR}
        - WP_PWD=${WP_PWD}
        - WP_EMAIL=${WP_EMAIL}
    environment:
      - DOMAIN_NAME
      - DB_NAME
      - WP_ADMIN_USR
      - WP_ADMIN_PWD
      - WP_ADMIN_EMAIL
      - WP_TITLE
      - WP_USR
      - WP_PWD
      - WP_EMAIL
    networks:
      - inception
    expose:
      - 9000
    restart: on-failure
############################### NGINX ##########################################
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
     - 443:443
    depends_on:
      - wordpress
    volumes:
     - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: on-failure
