version: "3.8"

networks:
  inception:
    name: inception

volumes:
        wordpress_volume:
                name: wordpress
                driver_opts:
                        device: /home/angomes/data/wordpress 
                        o: bind
                        type: none
        mariadb_volume:
                name: mariadb
                driver_opts:
                        device: /home/angomes/data/mariadb
                        o: bind
                        type: none

services:
############################### MARIADB ##########################################
  mariadb:
    container_name: mariadb
    image: mariadb:42
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    build:
      context: requirements/mariadb
      args:
        - ADMIN_USR=${ADMIN_USR}
        - ADMIN_PWD=${ADMIN_PWD}
        - DB_NAME=${DB_NAME}
    environment:
      - DB_NAME
      - ADMIN_USR
      - ADMIN_PWD
    networks:
      - inception
    expose:
      - 3306
    restart: on-failure
############################### WORDPRESS ##########################################
  wordpress:
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    build:
      context: requirements/wordpress
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - DB_NAME=${DB_NAME}
        - ADMIN_USR=${ADMIN_USR}
        - ADMIN_PWD=${ADMIN_PWD}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - TITLE=${TITLE}
        - USR_NAME=${USR_NAME}
        - USR_PWD=${USR_PWD}
        - USR_EMAIL=${USR_EMAIL}
    environment:
      - DOMAIN_NAME
      - DB_NAME
      - ADMIN_USR
      - ADMIN_PWD
      - ADMIN_EMAIL
      - TITLE
      - USR_NAME
      - USR_PWD
      - USR_EMAIL
    networks:
      - inception
    expose:
      - 9000
    restart: on-failure
############################### NGINX ##########################################
  nginx:
    container_name: nginx
    image: nginx:42
    build:
      context: requirements/nginx
      args:
      - CERTS_CRT=${CERTS_CRT}
      - CERTS_KEY=${CERTS_KEY}
    environment:
    - CERTS_KEY
    - CERTS_CRT
    ports:
     - 443:443
    depends_on:
      - wordpress
      - mariadb
    volumes:
     - wordpress_volume:/var/www/html
    networks:
      - inception
    restart: on-failure
